export { default as IconGitHub } from './IconGitHub.vue'
export { default as IconGoogle } from './IconGoogle.vue'
export { default as IconMail } from './IconMail.vue'
export { default as IconTelephone } from './IconTelephone.vue'
export { default as IconWeChat } from './IconWeChat.vue'